### ISSUE TITLE
HW #4 - First attempts at styling

### ISSUE THREAD

**Issue by hobertro** [teresa210/portfolio#10]
- Please create a new branch called hw-4
- EZ ONE COMMIT PER DAY ASSIGNMENT: Please create a new file called post-4.html and make a commit.
- I am not sure if you are familiar with css yet, but do not use any CSS for this HW
- In the file add h1 div with text "Sellbrite Team"
- Use a hr tag right below it. See: https://www.geeksforgeeks.org/html-hr-tag/
- Create a new table with 3 columns. First column header is "name", second column "team",  third column is leadership.
- Please add all of sellbrite members to the table with name, the team they are, and true or false if they are leadership.
- Today we will experiment with html attributes. Please read about them here: https://www.w3schools.com/html/html_attributes.asp
- We will experiment specifically with the style attribute. In your table, th, td tags, please add a 1px solid black border. Set id to "sb-team"
- Please span the width of the table to 100%. The table should span the width of the entire page
- For anyone in the CS team, set the text of their name to yellow. For all others, set the text of their name to blue. However, if they are leadership, set the text of their name to red. See: 
- Please align the names to the center. See: https://www.w3schools.com/tags/att_td_align.asp
- You might notice your table doesn't look like mine. Please see the https://www.w3schools.com/cssref/pr_border-collapse.asp to fix issue. Experiment with what the different options look like, but in the end make it look like my example.
![Screen Shot 2020-03-24 at 3 16 21 PM](https://user-images.githubusercontent.com/2173819/77482124-715a4800-6de2-11ea-9fb3-a7de98dd977f.png)
- Make PR and link back under here. Screen shot your example INSIDE of the pull request.
- Extra credit: set the font size of our names to 14px. The table won't look like mine now as the names will look like a bigger font
- Good luck!

**Comment by teresa210** [comment]
https://github.com/teresa210/portfolio/pull/11#issue-393839427

**Comment by hobertro** [comment]
:shipit:
