### ISSUE TITLE
HW# 10

### ISSUE THREAD

**Issue by hobertro** [teresa210/portfolio#20]
- I realized that there are two mistakes from your previous PR. You have a div and a p tag that both have two classes but it is not implemented correctly. Please fix them. Hint: I don't see a margin of 40px being applied.
- Add links to your github and linkedin. When I click on those links I expect to be taken to your github and linkedin respectively.
- Make PR when ready

**Comment by teresa210** [comment]
https://github.com/teresa210/portfolio/pull/23#issue-402966264

**Comment by hobertro** [comment]
nice TT
