### ISSUE TITLE
HW 3/18/20

### ISSUE THREAD

**Issue by hobertro** [teresa210/portfolio#4]
- Create a new branch, name it anything you want.
- In your posts div in the index.html file, create a h1 tag that that says "Posts" (should be below your picture) that is above your first post link.
- Create another file, called it "second-post.html." 
- Create a link to it. But for this link, we want it to open to a new window. Also use the li tag. We should see another bullet point for the second link. Example here: 
https://www.thesitewizard.com/html-tutorial/open-links-in-new-window-or-tab.shtml
- Inside the second-post.html, please copy the same for what you did for first-post except this time write about the different HTML tags you have learned
- For one of the the examples of what you learned/did for HTML tags, please use the "strong" tag. 
Learn about it here to see what it does: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/strong. If you don't want to read about it, just use it and see what happens haha.
- Make PR, screen shot your work, add to the description of the PR and link me as a comment of this issue

**Comment by teresa210** [comment]
https://github.com/teresa210/portfolio/pull/5#issue-391925792

is this the link to the PR?
